### ISSUE TITLE
IP Camera Stream Funktioniert nicht

### ISSUE THREAD

**Issue by Balu0127** [OpenAutomationProject/knx-uf-iconset#2]
Hallo

Leider Funktioniert das einbinden meiner IP Kameras nicht mehr.
Die Neuen Kameras haben eine Andere HTTP Anmeldung.
Alt 
http://192.168.***.**/admin&pwd=admin
Als erstes die IP und dann die Zugangsdaten.

Neu
http://admin:Passwort@ip-adresse:Port
Als erstes die Zugangsdaten und dann die IP

Gibt´s dafür eine Lösung?

Hello

Unfortunately, integrating my IP cameras no longer works.
The new cameras have a different HTTP registration.
Old
http: //192.168.***.**/admin&pwd=admin
First the IP and then the access data.

New
http: // admin: password @ ip-adress: port
First the access data and then the IP

Is there a solution for this?

**Comment by Apollon77** [comment]
Is this issue right here?!

**Comment by ChristianMayer** [comment]
Off topic
