### ISSUE TITLE
Some icons have stray artifacts in Home Assistant

### ISSUE THREAD

**Issue by P3TACCO** [OpenAutomationProject/knx-uf-iconset#7]
Using version 1.1.0 of KNX User Forum Icons set loaded into Home Assistant through HACS.

Several icons have spurious artifacts/errors

scene_freezer
scene_dishwasher
scene_washing_machine

All have the same error, what looks like a descending bar graph in the lower right hand corner of the icon.
This error is not present in the SVG or PNG files.  There may be other icons with this same error.  I'm using some of the other "scene" series and they do not have the error.
Since it is an identical error, it is likely stray code in the .js file.

I've tried to delete/ reinstall the repository with the same result.
I tried downloading version 1.0.0 and 1.0.1 and both have the same errors.

**Comment by P3TACCO** [comment]
![KNX_icon_errors](https://github.com/OpenAutomationProject/knx-uf-iconset/assets/128305263/0e354d92-1178-4605-9820-5a4d91e79c9d)

**Comment by P3TACCO** [comment]
I just discovered the measure_battery icons all have the same image

measure_battery_0
measure_battery_100
measure_battery_75
measure_battery_50
measure_battery_25

All display the measure_battery_100 icon

**Comment by ChristianMayer** [comment]
This must be an issue with how you are using the icons. In the raw file (e.g. https://github.com/OpenAutomationProject/knx-uf-iconset/blob/master/raw_svg/scene_freezer.svg ) you can see that the icon is as intended.

Also you can see that this are different icons:
https://github.com/OpenAutomationProject/knx-uf-iconset/blob/master/raw_svg/measure_battery_0.svg
https://github.com/OpenAutomationProject/knx-uf-iconset/blob/master/raw_svg/measure_battery_100.svg

**Comment by P3TACCO** [comment]
Yes, the svg and png images in the Github repository are correct.

When imported into Home Assistant through HACS the icons are not imported as svg or png files, they are in a single js file.
That js file appears to describe the icons with multiple vectors.  So the conversion from svg to that all up js file has errors included.
 

Home Assistant HACS install here
https://github.com/mampfes/ha-knx-uf-iconset

This is the file that contains the vector errors:
ha-knx-uf-iconset.js

ETA - it appears I should submit this issue there - I didn't realize these were different repositories.

**Comment by P3TACCO** [comment]
Wrong repository  :-)
